version: '2'

services:
  app:
    build: ./
    restart: always
    ports:
      - 8080:80
    environment:
      MAGE_ROOT_DIR: /var/www/html
    volumes:
      - app:/var/www/html
      - ./upload:/var/www/html/smailyfiles

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_ROOT_PASSWORD: smailydev1
    volumes:
      - database:/var/lib/mysql
volumes:
  app:
  database:
